# Generated by Django 6.1.1 on 2026-10-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_usage', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trad_dt', models.DateField()),
                ('tckr_symb', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=20)),
                ('fin_instrm_nm', models.CharField(blank=True, max_length=255)),
                ('cls_pric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prvs_clsg_pric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ttl_tradg_vol', models.BigIntegerField()),
                ('ttl_trf_val', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('scty_srs', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['tckr_symb', 'trad_dt'], name='api_bhavcop_tckr_sy_5f19d3_idx'), models.Index(fields=['trad_dt'], name='api_bhavcop_trad_dt_8d679d_idx')],
                'unique_together': {('trad_dt', 'tckr_symb', 'scty_srs')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckr_symb', models.CharField(db_index=True, max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('market_cap_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiscal_year', models.CharField(default='FY2025-26', max_length=20)),
                ('as_of_date', models.DateField()),
                ('source', models.CharField(default='Annual Report / BSE / NSE Corporate Filing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tckr_symb'], name='api_company_tckr_sy_e462d6_idx'), models.Index(fields=['as_of_date'], name='api_company_as_of_d_a96ec9_idx')],
                'unique_together': {('tckr_symb', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('input_args', models.JSONField()),
                ('output_result', models.JSONField()),
                ('latency_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='api.message')),
            ],
        ),
    ]
