# Generated by Django 5.2.6 on 2026-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='correlation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
