# Generated by Django 5.2.6 on 2026-10-01 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trad_dt', models.DateField()),
                ('tckr_symb', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=20)),
                ('fin_instrm_nm', models.CharField(blank=True, max_length=255)),
                ('cls_pric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prvs_clsg_pric', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ttl_tradg_vol', models.BigIntegerField()),
                ('ttl_trf_val', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('scty_srs', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['tckr_symb', 'trad_dt'], name='api_bhavcop_tckr_sy_5f19d3_idx'), models.Index(fields=['trad_dt'], name='api_bhavcop_trad_dt_8d679d_idx')],
                'unique_together': {('trad_dt', 'tckr_symb', 'scty_srs')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('input_args', models.JSONField()),
                ('output_result', models.JSONField()),
                ('latency_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='api.message')),
            ],
        ),
    ]
