# Generated by Django 5.2.6 on 2026-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_correlation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='correlation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
