# Generated by Django 6.1.1 on 2026-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bhavcopy_message_toolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tckr_symb', models.CharField(db_index=True, max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('market_cap_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_yield_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiscal_year', models.CharField(default='FY2025-26', max_length=20)),
                ('as_of_date', models.DateField()),
                ('source', models.CharField(default='Annual Report / BSE / NSE Corporate Filing', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tckr_symb'], name='api_company_tckr_sy_e462d6_idx'), models.Index(fields=['as_of_date'], name='api_company_as_of_d_a96ec9_idx')],
                'unique_together': {('tckr_symb', 'fiscal_year')},
            },
        ),
    ]
